### ISSUE TITLE
stacks and queue coding challenge

### ISSUE THREAD

**Issue by mattiaerre** [mattiaerre/another-table#12]
# Description

during today's interview, I've enjoyed very much @jknight12882 's question about how to implement a queue using stacks; I'd love to incorporate that challenge into this repo

**Comment by scottlepich** [comment]
This is a cool addition.  Would like to keep adding interviewing to this repo!

**Comment by mattiaerre** [comment]
yes please do @scottlepich I've also added a `interview` tag we can use w/ the PR we make
